# Generated by Django 4.1.5 on 2023-01-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bat", models.CharField(blank=True, max_length=30, null=True)),
                ("color_r", models.IntegerField(default=0)),
                ("color_g", models.IntegerField(default=0)),
                ("color_b", models.IntegerField(default=0)),
                ("encoder_l", models.IntegerField(default=0)),
                ("encoder_r", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
